{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "festivals.fullname" . }}-admin
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "festivals.admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "festivals.admin.selectorLabels" . | nindent 4 }}
{{- end }}
