{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "festivals.secretName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "festivals.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.dbUser }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtRefreshSecret }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.stripeSecretKey }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.stripeWebhookSecret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripeWebhookSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  {{- end }}
  {{- if .Values.secrets.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.s3Bucket }}
  S3_BUCKET: {{ .Values.secrets.s3Bucket | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.sendgridApiKey }}
  SENDGRID_API_KEY: {{ .Values.secrets.sendgridApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.firebaseServiceAccount }}
  FIREBASE_SERVICE_ACCOUNT: {{ .Values.secrets.firebaseServiceAccount | quote }}
  {{- end }}
  {{- if .Values.secrets.sentryDsn }}
  SENTRY_DSN: {{ .Values.secrets.sentryDsn | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.appleClientSecret }}
  APPLE_CLIENT_SECRET: {{ .Values.secrets.appleClientSecret | quote }}
  {{- end }}
{{- end }}
